### PR TITLE
SSO and video support for VKontakte

### PR DESCRIPTION
**Pull request by agrytsiuk**
VKontakte changes:
SSO support was implemented.
Now it's possible to share video directly to user's wall. Previously it was shared as a document. Not as a video.

### CODE REVIEW

**Comment by VilemKurz** [comment]
Still needs work. I tried to post video in the demo app, and got this error:
Access denied: no access to call this method

**Comment by agrytsiuk** [comment]
This error was returned cause you haven't specified the scope that is needed to post the video. I've moved the appropriate method to the SHKDefaultConfigurator. For video you should pass @[@"wall", @"video"]. By default only @"wall" scope is requested. It is up to developer that uses ShareKit to decide what scope to specify.

**Comment by VilemKurz** [comment]
To avoid this error, the functionality might be like this:

1. If there is no video in configurator, use old fashion file share for videos.
2. Make @[@"wall", @"video"] the default in DefaultSHKConfigurator, so that people can use this right away.

**Comment by agrytsiuk** [comment]
I've added photo,video,docs scope to VK

**Comment by VilemKurz** [comment]
Thank you, merged.

**Pull request merged**
